name: "Continuous Integration"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install python 3.12
        run: uv python install 3.12
      - name: Run coverage
        run: uv run pytest --cov tjost --cov-report xml
      - name: Build code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  lint:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run linting
        uses: astral-sh/ruff-action@v3

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Run tests
        run: uv run pytest

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
    permissions:
      id-token: write
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install python 3.12
        run: uv python install 3.12
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish
